# Generated by Django 2.2.6 on 2022-04-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
